// 生成常见密码名单 server/internal/modules/identity/domain/common_passwords.txt（M2 设计 3.8）。
//
// 用法：node tools/password-blocklist/build.mjs <PwnedPasswordsTop100k.txt>
//
// 原文件是英国国家网络安全中心（NCSC）发布的泄露最多的前 10 万个密码，不进仓库。NCSC 的原地址
// 已失效（2026-09 实测 404）；SecLists 收录的是同一个文件（SHA-256 相同），从这里下载：
//   https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt
// 脚本先核对它的 SHA-256，再只留下运行时的两种查找可能命中的条目（小写的整个密码、主干），
// 转小写、去重、按 UTF-8 字节排序（Go 的 sort.Strings 的顺序），写出文件头和名单。
// 主干的规则必须与 Go 的 identity/domain.core 相同；Go 的单元测试核对名单满足这里的过滤条件。
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const NCSC_URL = "https://www.ncsc.gov.uk/static-assets/documents/PwnedPasswordsTop100k.txt";
const SECLISTS_PATH = "Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt";
const SOURCE_SHA256 = "c2e5696882c603b76bb67a47ee970897e5a76fc4c3f5547abe3d0ca340c576e0";
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../server/internal/modules/identity/domain/common_passwords.txt"
);

// 组合规则的特殊字符，与 web/packages/utils/src/auth.ts 的 getPasswordStrength 相同。
const SPECIAL = `!@#$%^&*()-_+=[]{}|;:'",.<>?/`;
const hasSpecial = (s) => [...s].some((c) => SPECIAL.includes(c));
const asciiLetters = (s) => (s.match(/[a-z]/g) ?? []).length;
// 主干：小写后从两端去掉所有不是字母（Unicode 字母类）的字符。
const core = (s) => s.toLowerCase().replace(/^[^\p{L}]+|[^\p{L}]+$/gu, "");

// e（已转小写）被留下，当且仅当：
// 1. 某个满足组合规则的密码转小写后等于 e：长度 8–128，至少两个 ASCII 字母（一个可改成大写）、一个数字、一个特殊字符；
// 2. 或者某个满足组合规则的密码的主干等于 e：e 的主干是它自己，至少两个 ASCII 字母，
//    长度不超过 126（数字和特殊字符可以在去掉的两端）。
// 长度按 UTF-16 码元计，与界面的 password.length 相同。
const matchesInFull = (e) =>
  e.length >= 8 && e.length <= 128 && asciiLetters(e) >= 2 && /[0-9]/.test(e) && hasSpecial(e);
const matchesAsCore = (e) => e.length > 0 && e.length <= 126 && core(e) === e && asciiLetters(e) >= 2;

const [source] = process.argv.slice(2);
if (!source) {
  console.error("usage: node tools/password-blocklist/build.mjs <PwnedPasswordsTop100k.txt>");
  process.exit(2);
}
const data = readFileSync(source);
const sha256 = createHash("sha256").update(data).digest("hex");
if (sha256 !== SOURCE_SHA256) {
  console.error(`${source}: SHA-256 is ${sha256}, want ${SOURCE_SHA256}`);
  process.exit(1);
}
const entries = new Set(
  data
    .toString("utf8")
    .split(/\r?\n/)
    .filter(Boolean)
    .map((s) => s.toLowerCase())
);
const kept = [...entries]
  .filter((e) => matchesInFull(e) || matchesAsCore(e))
  .toSorted((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)));

const header = [
  "# Common passwords that Nerve rejects (M2 design 3.8). Generated by",
  "# tools/password-blocklist/build.mjs; do not edit.",
  "#",
  "# Source: PwnedPasswordsTop100k.txt, the NCSC list of the 100,000 passwords most",
  "# used in breaches, from Have I Been Pwned. NCSC published it at",
  `# ${NCSC_URL}`,
  "# (gone since); SecLists keeps the same file as",
  `# ${SECLISTS_PATH}.`,
  `# SHA-256 ${SOURCE_SHA256}`,
  "# Contains public sector information licensed under the Open Government Licence v3.0:",
  "# https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
  "#",
  "# Kept: the lowercased entries that a password passing the composition rules can",
  "# equal in full (8-128 characters, two ASCII letters, a digit, a special character)",
  "# or as its core (the entry is its own core, has two ASCII letters and at most 126",
  "# characters). One per line, sorted by bytes, after the blank line below.",
];
writeFileSync(OUT, `${header.join("\n")}\n\n${kept.join("\n")}\n`);
console.log(`${source}: ${entries.size} distinct lowercased entries, kept ${kept.length} in ${OUT}`);
