// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

// FieldError One invalid field of a request.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Problem RFC 9457 problem details (v0 design 3.5). `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it.
type Problem struct {
	// Code Stable error code. Platform codes have no prefix (not_found, bad_request, internal_error, not_ready); module codes are prefixed with the module, e.g. issue.state_not_in_project.
	Code string `json:"code"`

	// Detail What went wrong in this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors The invalid fields of the request.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title HTTP status phrase, e.g. "Not Found".
	Title string `json:"title"`
}
