/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Creates an account with its default profile and signs it in: the response holds a new session's tokens. While sign-up is off, a well-formed request answers identity.signup_disabled before the address or the password is looked at, so the answer never depends on whether the address is registered. The password needs 8–128 characters with an upper-case letter, a lower-case letter, a digit and a special character, and must not be a common password. Registrations have a rate limit of their own per client IP.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an e-mail address and a password
         * @description Starts a new session and returns its tokens. An unknown address and a wrong password get the same identity.invalid_credentials; a deactivated account answers identity.account_deactivated only to the right password. Logins have rate limits of their own: per client IP, and per client IP and address together.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for the next pair
         * @description Returns new tokens of the same session and retires the refresh token sent: the next refresh uses the refresh_token of this response. The session's end, refresh_token_expires_at, never moves. Any refresh token but the current one of a session that has not ended answers identity.refresh_token_invalid; one this session issued before also ends the session, since someone else holds a copy of it.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session of a refresh token
         * @description Ends the session when refresh_token is its current one. Any other token changes nothing and gets the same answer, which tells nothing about the token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @description The sign-in address; stored trimmed and in lower case.
             */
            email: string;
            password: string;
        };
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request body, e.g. password or tags[1].name. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "weak_password" | "common_password" | "must_be_future" | "contains_url";
            message: string;
        };
        /** @description RFC 9457 problem details (v0 design 3.5). `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module, e.g. identity.email_taken. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description A session's tokens. Send access_token as "Authorization: Bearer"; when it expires, exchange refresh_token for the next pair at POST /api/v0/auth/refresh. */
        AuthTokens: {
            /** @enum {string} */
            token_type: "Bearer";
            access_token: string;
            /** @description Seconds from this response until the access token expires. */
            access_token_expires_in: number;
            /** @description An opaque nrv_rt_ token. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the session ends; refreshing never extends it.
             */
            refresh_token_expires_at: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description The sign-in address, in any case, with or without surrounding blanks.
             */
            email: string;
            password: string;
        };
        RefreshRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        LogoutRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            display_name: string;
            /** @description An IANA time zone name. */
            user_timezone: string;
            /** @description Null until uploads arrive (M5). */
            avatar_url: string | null;
            /** @description Null until uploads arrive (M5). */
            cover_image_url: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                /** @description Sent with every 401 (RFC 9110 15.5.2): Bearer, or Bearer error="invalid_token" when the bearer token sent is invalid or has expired (RFC 6750 3). */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The new session's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The session's next tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Done, whatever the token was. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
