/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Creates an account with its default profile and signs it in: the response holds a new session's tokens. While sign-up is off, a well-formed request answers identity.signup_disabled before the address or the password is looked at, so the answer never depends on whether the address is registered. The password needs 8–128 characters with an upper-case letter, a lower-case letter, a digit and a special character, and must not be a common password. Registrations have a rate limit of their own per client IP.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an e-mail address and a password
         * @description Starts a new session and returns its tokens. An unknown address and a wrong password get the same identity.invalid_credentials; a deactivated account answers identity.account_deactivated only to the right password. Logins have rate limits of their own: per client IP, and per client IP and address together.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for the next pair
         * @description Returns new tokens of the same session and retires the refresh token sent: the next refresh uses the refresh_token of this response. The session's end, refresh_token_expires_at, never moves. Any refresh token but the current one of a session that has not ended answers identity.refresh_token_invalid; one this session issued before under the current signing key also ends the session, since someone else holds a copy of it.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session of a refresh token
         * @description Ends the session when refresh_token is its current one. Any other token changes nothing and gets the same answer, which tells nothing about the token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's names and time zone
         * @description Changes the fields sent and leaves the others. The e-mail address cannot change here: the server's administrator changes it with `nerve users set-email`, which signs every session out.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v0/me/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate the caller's account
         * @description Any credential may, a personal access token too; no password is asked for. Every session is signed out and onboarding starts over. The password and the personal access tokens stay, but nothing authenticates as the account until the server's administrator activates it again with `nerve users activate`; then its unexpired personal access tokens authenticate again.
         */
        post: operations["deactivateMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the caller's password
         * @description Needs the current password. The new one follows the rules of registration. Every other session of the account is signed out: all of them when the caller is a personal access token. Personal access tokens keep working. Password changes have a rate limit of their own per account.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's preferences */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's preferences
         * @description Changes the fields sent and leaves the others. The onboarding steps sent are merged into the stored ones: a step not sent keeps its value, also when another request changes it at the same time.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v0/me/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's personal access tokens
         * @description The caller's personal access tokens that are not revoked, newest first, a page at a time. The tokens themselves are never listed: only createApiToken answers one, once.
         */
        get: operations["listApiTokens"];
        put?: never;
        /**
         * Create a personal access token
         * @description Creates a personal access token of the caller and answers the token itself, this once. Sent as "Authorization: Bearer", it acts as the account in every operation until it expires or is revoked, and it can create tokens itself. Any credential may create one; no password is asked for.
         */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/api-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal access token
         * @description Revokes one of the caller's tokens, which stops working at once; a token may revoke itself. A token that does not exist, is revoked already or belongs to another account is identity.api_token_not_found.
         */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs, and the settings clients adapt to. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/timezones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the time zones to choose from
         * @description The time zones the web app offers, each with its offset at the time of the request, sorted by offset and then by label. user_timezone takes any IANA name, not only these. Public: needs no authentication.
         */
        get: operations["listTimezones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's workspaces
         * @description The workspaces of which the caller is an active member, each with the caller's role and the number of active members, by name and then by id. The whole collection at once: collections are not paginated.
         */
        get: operations["listWorkspaces"];
        put?: never;
        /**
         * Create a workspace with the caller as its admin
         * @description Creates the workspace and makes the caller its admin and only member; nothing else is created with it. While the instance's workspace_creation_enabled is false, an authenticated, well-formed request answers workspace.creation_disabled before its values are looked at, and the server's administrator creates workspaces with `nerve workspaces create`. The name has 1–80 characters with a letter or a digit and no web address, and a NUL character in it is refused (invalid_format); the slug has 1–48 lower-case letters, digits, - and _, and is neither reserved (not_allowed) nor another undeleted workspace's (workspace.slug_taken). An account deactivated meanwhile answers unauthorized.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Read a workspace
         * @description A workspace that does not exist, is deleted, or of which the caller is not an active member answers the same workspace.not_found.
         */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /**
         * Delete a workspace
         * @description For the workspace's admins. The workspace, its memberships and the members' display settings are soft-deleted in one transaction, at the same moment; the members' accounts stay. The slug can name a new workspace at once. Nobody's last_workspace_id is cleared. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden.
         */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /**
         * Change a workspace's name, organization size or time zone
         * @description For the workspace's admins. The fields given change and the others stay; the values follow createWorkspace's rules (validation_failed), checked before the workspace is looked at. The slug never changes: a body with slug is refused (bad_request). A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden. The role is decided after the workspace row is locked, so a caller demoted meanwhile is refused.
         */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/api/v0/workspaces/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * List a workspace's members
         * @description Every membership of the workspace, those that ended too (is_active false), in the order they began, then by id, each with the member's public profile. For any active member. The addresses are shown to admins and members; to a guest every address is null, his own too. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found. The whole collection at once: collections are not paginated.
         */
        get: operations["listWorkspaceMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspace-members/{workspace_member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A membership's id (WorkspaceMember.id), not the member's account id. */
                workspace_member_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description For the workspace's admins. The role is checked first (validation_failed). A membership that does not exist or is deleted, or whose workspace the caller cannot see, answers workspace.member_not_found; a member or a guest, forbidden, whatever the membership. To a caller who may change roles, a membership that has ended answers workspace.member_not_found, and his own workspace.own_membership: nobody changes his own role. The role is decided after the workspace row is locked, so of two admins who demote each other at once only the first succeeds and the workspace keeps an admin.
         */
        patch: operations["updateWorkspaceMember"];
        trace?: never;
    };
    "/api/v0/workspace-slugs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Tell whether a slug can name a new workspace
         * @description Available, or why not: invalid (not 1–48 lower-case letters, digits, - and _), reserved (a path of this site, or held for one), or taken (an undeleted workspace has it). It tells nothing about the workspace that has it.
         */
        get: operations["checkWorkspaceSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/workspaces/{slug}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Read the caller's display settings in a workspace
         * @description The caller's own settings of the sidebar's project navigation in the workspace, for any active member. Until the caller first changes them they are the defaults, ACCORDION and 10, and reading them writes nothing. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found.
         */
        get: operations["getWorkspacePreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's display settings in a workspace
         * @description The fields given change and the others stay; the first change stores the caller's settings, the defaults with the change applied. The values are checked before the workspace is looked at (validation_failed). A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found.
         */
        patch: operations["updateWorkspacePreferences"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @description The sign-in address; stored trimmed and in lower case.
             */
            email: string;
            password: string;
        };
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request body, e.g. password or tags[1].name. A path longer than 256 bytes is cut short and ends with `…`. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "duplicate" | "weak_password" | "common_password" | "must_be_future" | "contains_url";
            message: string;
        };
        /** @description RFC 9457 problem details (v0 design 3.5). `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module that refuses, e.g. identity.email_taken, whichever module's operation answers them. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description A session's tokens. Send access_token as "Authorization: Bearer"; when it expires, exchange refresh_token for the next pair at POST /api/v0/auth/refresh. */
        AuthTokens: {
            /** @enum {string} */
            token_type: "Bearer";
            access_token: string;
            /** @description Seconds from this response until the access token expires. */
            access_token_expires_in: number;
            /** @description An opaque nrv_rt_ token. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the session ends; refreshing never extends it.
             */
            refresh_token_expires_at: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description The sign-in address, in any case, with or without surrounding blanks.
             */
            email: string;
            password: string;
        };
        RefreshRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        LogoutRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            display_name: string;
            /** @description An IANA time zone name. */
            user_timezone: string;
            /** @description Null until uploads arrive (M5). */
            avatar_url: string | null;
            /** @description Null until uploads arrive (M5). */
            cover_image_url: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserUpdate: {
            /** @description At most 255 characters, without a web address. */
            first_name?: string;
            /** @description At most 255 characters, without a web address. */
            last_name?: string;
            /** @description 1–255 characters. */
            display_name?: string;
            /** @description An IANA time zone name, e.g. from GET /api/v0/timezones. */
            user_timezone?: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @enum {string} */
        Theme: "system" | "light" | "dark" | "light-contrast" | "dark-contrast";
        /**
         * @description The language of the web UI.
         * @enum {string}
         */
        Language: "en" | "zh-CN";
        /**
         * @description The first day of the week, 0 Sunday to 6 Saturday.
         * @enum {integer}
         */
        StartOfTheWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        OnboardingSteps: {
            profile_complete: boolean;
            workspace_create: boolean;
            workspace_invite: boolean;
            workspace_join: boolean;
        };
        Profile: {
            theme: components["schemas"]["Theme"];
            language: components["schemas"]["Language"];
            start_of_the_week: components["schemas"]["StartOfTheWeek"];
            onboarding_step: components["schemas"]["OnboardingSteps"];
            is_onboarded: boolean;
            is_tour_completed: boolean;
            /**
             * Format: uuid
             * @description The workspace the web app opens last; null for none. It is not checked to exist.
             */
            last_workspace_id: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description The steps to set; the others keep their values. */
        OnboardingStepsUpdate: {
            profile_complete?: boolean;
            workspace_create?: boolean;
            workspace_invite?: boolean;
            workspace_join?: boolean;
        };
        ProfileUpdate: {
            theme?: components["schemas"]["Theme"];
            language?: components["schemas"]["Language"];
            start_of_the_week?: components["schemas"]["StartOfTheWeek"];
            onboarding_step?: components["schemas"]["OnboardingStepsUpdate"];
            is_onboarded?: boolean;
            is_tour_completed?: boolean;
            /**
             * Format: uuid
             * @description Null clears it.
             */
            last_workspace_id?: string | null;
        };
        /** @description A personal access token as lists show it. The token itself appears only in ApiTokenCreated. */
        ApiToken: {
            /** Format: uuid */
            id: string;
            label: string;
            description: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expired_at: string | null;
            /**
             * Format: date-time
             * @description When the token last authenticated a request, to the minute; null when it never has.
             */
            last_used: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description The cursor of the next page; null on the last page. */
        NextCursor: string | null;
        ApiTokenPage: {
            data: components["schemas"]["ApiToken"][];
            next_cursor: components["schemas"]["NextCursor"];
        };
        ApiTokenCreate: {
            /** @description 1–255 characters; 32 hexadecimal digits are made up when it is absent. */
            label?: string;
            description?: string;
            /**
             * Format: date-time
             * @description A time in the future; absent or null for a token that never expires.
             */
            expired_at?: string | null;
        };
        /** @description A new personal access token: the fields of ApiToken, and the token itself, which is shown this once and cannot be read again. */
        ApiTokenCreated: {
            /** Format: uuid */
            id: string;
            label: string;
            description: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expired_at: string | null;
            /**
             * Format: date-time
             * @description Null; the token has not been used yet.
             */
            last_used: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description The token, nrv_pat_ and 43 more characters. */
            token: string;
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
            /** @description Whether anyone may register (auth.signup_enabled). */
            signup_enabled: boolean;
            /** @description Whether workspaces can be created (workspace.creation_enabled). */
            workspace_creation_enabled: boolean;
            /** @description The largest file an upload may have, in bytes (files.size_limit). */
            file_size_limit: number;
        };
        Timezone: {
            /** @description A place in the time zone, e.g. Beijing. */
            label: string;
            /**
             * @description The IANA name, what user_timezone takes.
             * @example Asia/Shanghai
             */
            value: string;
            /**
             * @description The offset at the time of the request.
             * @example UTC+08:00
             */
            utc_offset: string;
            /**
             * @description The same offset, written from GMT.
             * @example GMT+08:00
             */
            gmt_offset: string;
        };
        TimezoneList: {
            data: components["schemas"]["Timezone"][];
        };
        /**
         * @description A member's role in a workspace, 5 guest, 15 member, 20 admin.
         * @enum {integer}
         */
        WorkspaceRole: 5 | 15 | 20;
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Lower case; it never changes. */
            slug: string;
            /** @description One of OrganizationSize's values; null when none was given. */
            organization_size: string | null;
            /** @description An IANA time zone name. */
            timezone: string;
            /** @description Null until uploads arrive (M5). */
            logo_url: string | null;
            role: components["schemas"]["WorkspaceRole"];
            /** @description The number of active members. */
            total_members: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkspaceList: {
            data: components["schemas"]["Workspace"][];
        };
        /**
         * @description The size of the organization, as the web app's form offers it.
         * @enum {string}
         */
        OrganizationSize: "Just myself" | "2-10" | "11-50" | "51-200" | "201-500" | "500+";
        WorkspaceCreate: {
            /** @description 1–80 characters, with a letter or a digit, without a web address. */
            name: string;
            /** @description 1–48 lower-case letters, digits, - and _; not reserved. */
            slug: string;
            organization_size?: components["schemas"]["OrganizationSize"];
            /** @description An IANA time zone name, e.g. from GET /api/v0/timezones; UTC when not given. */
            timezone?: string;
        };
        /** @description Changes the fields it names; a field left out keeps its value. organization_size cannot be set to null. */
        WorkspaceUpdate: {
            /** @description 1–80 characters, with a letter or a digit, without a web address. */
            name?: string;
            organization_size?: components["schemas"]["OrganizationSize"];
            /** @description An IANA time zone name. */
            timezone?: string;
        };
        /** @description A member's public profile, embedded in the membership: the one way v0 shows other accounts (M3 design 5.2). */
        MemberUser: {
            /** Format: uuid */
            id: string;
            display_name: string;
            first_name: string;
            last_name: string;
            /** @description Null until uploads arrive (M5). */
            avatar_url: string | null;
            /** @description The member's address for a caller who is an admin or a member; null for a guest. */
            email: string | null;
        };
        WorkspaceMember: {
            /**
             * Format: uuid
             * @description The membership's id, which /workspace-members/{workspace_member_id} names.
             */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            role: components["schemas"]["WorkspaceRole"];
            /** @description False once the membership has ended. */
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            member: components["schemas"]["MemberUser"];
        };
        WorkspaceMemberList: {
            data: components["schemas"]["WorkspaceMember"][];
        };
        WorkspaceMemberUpdate: {
            role: components["schemas"]["WorkspaceRole"];
        };
        SlugAvailability: {
            available: boolean;
            /**
             * @description Why the slug is not available; absent when it is.
             * @enum {string}
             */
            reason?: "invalid" | "reserved" | "taken";
        };
        /**
         * @description How the sidebar shows the projects, as sections one under another or as tabs.
         * @enum {string}
         */
        NavigationControlPreference: "ACCORDION" | "TABBED";
        /** @description How many projects the sidebar shows before "more"; 0 shows them all. */
        NavigationProjectLimit: number;
        WorkspacePreferences: {
            navigation_control_preference: components["schemas"]["NavigationControlPreference"];
            navigation_project_limit: components["schemas"]["NavigationProjectLimit"];
        };
        WorkspacePreferencesUpdate: {
            navigation_control_preference?: components["schemas"]["NavigationControlPreference"];
            navigation_project_limit?: components["schemas"]["NavigationProjectLimit"];
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                /** @description Sent with every 401 (RFC 9110 15.5.2): Bearer error="invalid_token" (RFC 6750 3) when the bearer token sent is refused before the operation runs, being invalid or expired; plain Bearer for every other 401, including a credential that the operation finds revoked while it runs. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The page size, 1–100; 50 when absent. Outside that range the answer is 422 validation_failed on limit. */
        Limit: number;
        /** @description The next_cursor of the page before; absent for the first page. A cursor that does not decode, has an unknown version or a payload of another shape than this list's, or is not spelled as the server writes it is 400 bad_request on cursor. */
        Cursor: string;
        /** @description A workspace's slug, as in the web app's address. */
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type FieldError = components['schemas']['FieldError'];
export type Problem = components['schemas']['Problem'];
export type AuthTokens = components['schemas']['AuthTokens'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type RefreshRequest = components['schemas']['RefreshRequest'];
export type LogoutRequest = components['schemas']['LogoutRequest'];
export type User = components['schemas']['User'];
export type UserUpdate = components['schemas']['UserUpdate'];
export type ChangePasswordRequest = components['schemas']['ChangePasswordRequest'];
export type Theme = components['schemas']['Theme'];
export type Language = components['schemas']['Language'];
export type StartOfTheWeek = components['schemas']['StartOfTheWeek'];
export type OnboardingSteps = components['schemas']['OnboardingSteps'];
export type Profile = components['schemas']['Profile'];
export type OnboardingStepsUpdate = components['schemas']['OnboardingStepsUpdate'];
export type ProfileUpdate = components['schemas']['ProfileUpdate'];
export type ApiToken = components['schemas']['ApiToken'];
export type NextCursor = components['schemas']['NextCursor'];
export type ApiTokenPage = components['schemas']['ApiTokenPage'];
export type ApiTokenCreate = components['schemas']['ApiTokenCreate'];
export type ApiTokenCreated = components['schemas']['ApiTokenCreated'];
export type InstanceInfo = components['schemas']['InstanceInfo'];
export type Timezone = components['schemas']['Timezone'];
export type TimezoneList = components['schemas']['TimezoneList'];
export type WorkspaceRole = components['schemas']['WorkspaceRole'];
export type Workspace = components['schemas']['Workspace'];
export type WorkspaceList = components['schemas']['WorkspaceList'];
export type OrganizationSize = components['schemas']['OrganizationSize'];
export type WorkspaceCreate = components['schemas']['WorkspaceCreate'];
export type WorkspaceUpdate = components['schemas']['WorkspaceUpdate'];
export type MemberUser = components['schemas']['MemberUser'];
export type WorkspaceMember = components['schemas']['WorkspaceMember'];
export type WorkspaceMemberList = components['schemas']['WorkspaceMemberList'];
export type WorkspaceMemberUpdate = components['schemas']['WorkspaceMemberUpdate'];
export type SlugAvailability = components['schemas']['SlugAvailability'];
export type NavigationControlPreference = components['schemas']['NavigationControlPreference'];
export type NavigationProjectLimit = components['schemas']['NavigationProjectLimit'];
export type WorkspacePreferences = components['schemas']['WorkspacePreferences'];
export type WorkspacePreferencesUpdate = components['schemas']['WorkspacePreferencesUpdate'];
export type ResponseProblem = components['responses']['Problem'];
export type ParameterLimit = components['parameters']['Limit'];
export type ParameterCursor = components['parameters']['Cursor'];
export type ParameterSlug = components['parameters']['Slug'];
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The new session's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The session's next tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Done, whatever the token was. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The caller's account, changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deactivateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's preferences. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The caller's preferences, changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listApiTokens: {
        parameters: {
            query?: {
                /** @description The page size, 1–100; 50 when absent. Outside that range the answer is 422 validation_failed on limit. */
                limit?: components["parameters"]["Limit"];
                /** @description The next_cursor of the page before; absent for the first page. A cursor that does not decode, has an unknown version or a payload of another shape than this list's, or is not spelled as the server writes it is 400 bad_request on cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description The new token, with the token itself. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTimezones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The time zones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimezoneList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description The new workspace; the caller is its admin. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace, with the caller's role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace is deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description The workspace as changed, with the caller's role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A membership's id (WorkspaceMember.id), not the member's account id. */
                workspace_member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberUpdate"];
            };
        };
        responses: {
            /** @description The membership with its new role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    checkWorkspaceSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the slug is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlugAvailability"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkspacePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's settings in the workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePreferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspacePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePreferencesUpdate"];
            };
        };
        responses: {
            /** @description The caller's settings in the workspace, as changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePreferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
