/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Creates an account with its default profile and signs it in: the response holds a new session's tokens. While sign-up is off, a well-formed request answers identity.signup_disabled before the address is validated or looked up, so the answer never depends on whether the address is registered; unless it names an invitation whose link it holds, pending, to the address it registers (normalized). Every other invitation answers the same identity.signup_disabled, whatever is wrong with it. Once sign-up is allowed (it is on, or the request holds such a link), registration answers as usual: validation_failed for a weak password, identity.email_taken for an address already registered, and neither creates an account. Registering does not accept the invitation. The password needs 8–128 characters with an upper-case letter, a lower-case letter, a digit and a special character, and must not be a common password. Registrations have a rate limit of their own per client IP.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an e-mail address and a password
         * @description Starts a new session and returns its tokens. An unknown address and a wrong password get the same identity.invalid_credentials; a deactivated account answers identity.account_deactivated only to the right password. Logins have rate limits of their own: per client IP, and per client IP and address together.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for the next pair
         * @description Returns new tokens of the same session and retires the refresh token sent: the next refresh uses the refresh_token of this response. The session's end, refresh_token_expires_at, never moves. Any refresh token but the current one of a session that has not ended answers identity.refresh_token_invalid; one this session issued before under the current signing key also ends the session, since someone else holds a copy of it.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session of a refresh token
         * @description Ends the session when refresh_token is its current one. Any other token changes nothing and gets the same answer, which tells nothing about the token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's names and time zone
         * @description Changes the fields sent and leaves the others. The e-mail address cannot change here: the server's administrator changes it with `nerve users set-email`, which signs every session out.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v0/me/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate the caller's account
         * @description Any credential may, a personal access token too; no password is asked for. Every session is signed out and onboarding starts over. The password and the personal access tokens stay, but nothing authenticates as the account until the server's administrator activates it again with `nerve users activate`; then its unexpired personal access tokens authenticate again.
         */
        post: operations["deactivateMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the caller's password
         * @description Needs the current password. The new one follows the rules of registration. Every other session of the account is signed out: all of them when the caller is a personal access token. Personal access tokens keep working. Password changes have a rate limit of their own per account.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's preferences */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's preferences
         * @description Changes the fields sent and leaves the others. The onboarding steps sent are merged into the stored ones: a step not sent keeps its value, also when another request changes it at the same time.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v0/me/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's personal access tokens
         * @description The caller's personal access tokens that are not revoked, newest first, a page at a time. The tokens themselves are never listed: only createApiToken answers one, once.
         */
        get: operations["listApiTokens"];
        put?: never;
        /**
         * Create a personal access token
         * @description Creates a personal access token of the caller and answers the token itself, this once. Sent as "Authorization: Bearer", it acts as the account in every operation until it expires or is revoked, and it can create tokens itself. Any credential may create one; no password is asked for.
         */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/api-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal access token
         * @description Revokes one of the caller's tokens, which stops working at once; a token may revoke itself. A token that does not exist, is revoked already or belongs to another account is identity.api_token_not_found.
         */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs, and the settings clients adapt to. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/timezones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the time zones to choose from
         * @description The time zones the web app offers, each with its offset at the time of the request, sorted by offset and then by label. user_timezone takes any IANA name, not only these. Public: needs no authentication.
         */
        get: operations["listTimezones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's workspaces
         * @description The workspaces of which the caller is an active member, each with the caller's role and the number of active members, by name and then by id. The whole collection at once: collections are not paginated.
         */
        get: operations["listWorkspaces"];
        put?: never;
        /**
         * Create a workspace with the caller as its admin
         * @description Creates the workspace and makes the caller its admin and only member; nothing else is created with it. While the instance's workspace_creation_enabled is false, an authenticated, well-formed request answers workspace.creation_disabled before its values are looked at, and the server's administrator creates workspaces with `nerve workspaces create`. The name has 1–80 characters with a letter or a digit and no web address, and a NUL character in it is refused (invalid_format); the slug has 1–48 lower-case letters, digits, - and _, and is neither reserved (not_allowed) nor another undeleted workspace's (workspace.slug_taken). An account deactivated meanwhile answers unauthorized.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Read a workspace
         * @description A workspace that does not exist, is deleted, or of which the caller is not an active member answers the same workspace.not_found.
         */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /**
         * Delete a workspace
         * @description For the workspace's admins. The workspace, its invitations, its memberships, the members' display settings, and its projects with their memberships, display settings and states are soft-deleted in one transaction, at the same moment; the members' accounts stay. The slug can name a new workspace at once. Nobody's last_workspace_id is cleared. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden.
         */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /**
         * Change a workspace's name, organization size or time zone
         * @description For the workspace's admins. The fields given change and the others stay; the values follow createWorkspace's rules (validation_failed), checked before the workspace is looked at. The slug never changes: a body with slug is refused (bad_request). A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden. The role is decided after the workspace row is locked, so a caller demoted meanwhile is refused.
         */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/api/v0/workspaces/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * List a workspace's members
         * @description Every membership of the workspace, those that ended too (is_active false), in the order they began, then by id, each with the member's public profile. For any active member. The addresses are shown to admins and members; to a guest every address is null, his own too. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found. The whole collection at once: collections are not paginated.
         */
        get: operations["listWorkspaceMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces/{slug}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * List a workspace's invitations
         * @description The workspace's invitations, pending and declined, newest first, then by id, each with the token of its link: for the workspace's admins alone. An accepted invitation is no longer listed. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden. The whole collection at once: collections are not paginated.
         */
        get: operations["listWorkspaceInvitations"];
        put?: never;
        /**
         * Invite addresses to a workspace
         * @description For the workspace's admins. Each address is normalized as at registration (surrounding white space removed, lower case) and the batch is checked first: 1–100 invitations, each address valid (invalid_format) and listed once (duplicate), each role one of the three (invalid_format). Then, the workspace looked at: an active member's address is not_allowed, and an address with an invitation to the workspace, pending or declined, duplicate, also when another request invites it at the same time. The batch is refused as a whole, one validation_failed naming each invitations[i] of the request as sent; a batch that loses the race to another request, which commits its addresses between this one's check and its insert, names only the first of them in the order of the normalized addresses. A declined invitation holds its address until it is deleted. The answer is the new invitations in the request's order, each with the token of its link. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a member or a guest, forbidden. A credential revoked meanwhile, by a password reset, answers unauthorized, and nothing is invited.
         */
        post: operations["createWorkspaceInvitations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspace-members/{workspace_member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A membership's id (WorkspaceMember.id), not the member's account id. */
                workspace_member_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description For the workspace's admins. The role is checked first (validation_failed). A membership that does not exist or is deleted, or whose workspace the caller cannot see, answers workspace.member_not_found; a member or a guest, forbidden, whatever the membership. To a caller who may change roles, a membership that has ended answers workspace.member_not_found, and his own workspace.own_membership: nobody changes his own role. The role is decided after the workspace row is locked, so of two admins who demote each other at once only the first succeeds and the workspace keeps an admin.
         */
        patch: operations["updateWorkspaceMember"];
        trace?: never;
    };
    "/api/v0/workspace-invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        /**
         * Show an invitation to whoever holds its link
         * @description Public: the link's token stands for a credential, and the answer is the same with a bearer token or without one. It shows the invitation's role, whether it was declined, and its workspace's name and slug; never the address invited. A token that is not the invitation's, and an invitation that does not exist, is deleted or accepted, answer the same workspace.invitation_not_found. Requests are limited per client IP.
         */
        get: operations["getWorkspaceInvitation"];
        put?: never;
        post?: never;
        /**
         * Delete an invitation
         * @description For the workspace's admins. The invitation, pending or declined, is soft-deleted: its link stops working, and its address can be invited again at once. An invitation that does not exist, is deleted or accepted, or whose workspace the caller cannot see, answers workspace.invitation_not_found; a member or a guest, forbidden.
         */
        delete: operations["deleteWorkspaceInvitation"];
        options?: never;
        head?: never;
        /**
         * Change an invitation's role
         * @description For the workspace's admins. The role is checked first (validation_failed). An invitation that does not exist, is deleted or accepted, or whose workspace the caller cannot see, answers workspace.invitation_not_found; a member or a guest, forbidden, whatever the invitation. To an admin, a declined invitation answers workspace.invitation_responded: delete it, then invite the address again. The link keeps its token.
         */
        patch: operations["updateWorkspaceInvitation"];
        trace?: never;
    };
    "/api/v0/workspace-invitations/{invitation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation to one's own address
         * @description For the account the invitation was sent to: its address, as it is when the request runs, must be the invitation's; another answers workspace.invitation_email_mismatch, which does not say whose, and nothing changes. The caller becomes a member with the invitation's role, or a former member has his membership back with it; an active member stays as he is, his role too, and only the invitation is used. The invitation is then accepted and deleted: its link stops working. A token that is not the invitation's, and an invitation that does not exist, is deleted or accepted, answer the same workspace.invitation_not_found; a declined one, workspace.invitation_responded. An account deactivated meanwhile answers unauthorized. The answer is the workspace, with the caller's role in it.
         */
        post: operations["acceptWorkspaceInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspace-invitations/{invitation_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline an invitation to one's own address
         * @description For the account the invitation was sent to, as accepting it is, with the same answers. The invitation stays, declined: its link shows so, and it holds its address until an admin deletes it.
         */
        post: operations["declineWorkspaceInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspace-slugs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Tell whether a slug can name a new workspace
         * @description Available, or why not: invalid (not 1–48 lower-case letters, digits, - and _), reserved (a path of this site, or held for one), or taken (an undeleted workspace has it). It tells nothing about the workspace that has it.
         */
        get: operations["checkWorkspaceSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/workspaces/{slug}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Read the caller's display settings in a workspace
         * @description The caller's own settings of the sidebar's project navigation in the workspace, for any active member. Until the caller first changes them they are the defaults, ACCORDION and 10, and reading them writes nothing. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found.
         */
        get: operations["getWorkspacePreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's display settings in a workspace
         * @description The fields given change and the others stay; the first change stores the caller's settings, the defaults with the change applied. The values are checked before the workspace is looked at (validation_failed). A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found.
         */
        patch: operations["updateWorkspacePreferences"];
        trace?: never;
    };
    "/api/v0/workspaces/{slug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * List a workspace's projects that the caller sees
         * @description The workspace's projects that the caller sees, each as he sees it: every one, to its admins; to its members, the public ones and those they are members of; to its guests, those they are members of. The archived projects are left out, unless archived is true, which lists them alone. By the caller's place of each in his sidebar, the projects he is not a member of last, then by name. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found. The whole collection at once: collections are not paginated.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project in a workspace
         * @description For the workspace's admins and members. The project is created with the caller, and the lead when one is given, as its admins, the project first in each one's sidebar, and with its six states: Backlog, the default, Todo, In Progress, Done, Cancelled and Triage. The name has 1–255 characters, not all spaces, without NUL and without any of & + , : ; $ ^ } { * = ? @ # | ' < > . ( ) % ! -; the identifier, upper-cased, has 1–10 of A-Z, 0-9 and ÇŞĞİÖÜ; the network is 0 or 2, public when not given; the time zone is an IANA name, the workspace's when not given (validation_failed). The values are checked before the workspace is looked at. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a guest, forbidden. The lead must be an active admin or member of the workspace (project_lead_id not_allowed), which is checked after the caller's role. Neither the name nor the identifier may be another undeleted project's of the workspace (project.name_taken, project.identifier_taken).
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workspaces/{slug}/project-identifiers/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
                /** @description An identifier asked about, in any case. */
                identifier: string;
            };
            cookie?: never;
        };
        /**
         * Check whether a project identifier is available in a workspace
         * @description For the workspace's admins and members, as createProject. The identifier is available when createProject would take it: once upper-cased, 1–10 of A-Z, 0-9 and ÇŞĞİÖÜ, and no undeleted project of the workspace's. A workspace that does not exist, is deleted, or of which the caller is not an active member answers workspace.not_found; a guest, forbidden.
         */
        get: operations["checkProjectIdentifier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A project's id (Project.id). */
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /**
         * Read a project
         * @description For whoever sees the project: its active members, the workspace's admins, and for a public project the workspace's members too; a caller who is not its member reads it with member_role and sort_order null. An archived project is read as any other, with its archived_at. A project that does not exist, is deleted, or that the caller does not see answers project.not_found; so does one whose workspace he is not an active member of.
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The invitation a registration names, from its link (/workspace-invitations?invitation_id=…&token=…): while sign-up is off, it lets the address it was sent to register. */
        RegisterInvitation: {
            /**
             * Format: uuid
             * @description The link's invitation_id.
             */
            id: string;
            /** @description The link's token. */
            token: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description The sign-in address; stored trimmed and in lower case.
             */
            email: string;
            password: string;
            invitation?: components["schemas"]["RegisterInvitation"];
        };
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request body, e.g. password or tags[1].name. A path longer than 256 bytes is cut short and ends with `…`. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "duplicate" | "weak_password" | "common_password" | "must_be_future" | "contains_url";
            message: string;
        };
        /** @description RFC 9457 problem details (v0 design 3.5). `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module that refuses, e.g. identity.email_taken, whichever module's operation answers them. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description A session's tokens. Send access_token as "Authorization: Bearer"; when it expires, exchange refresh_token for the next pair at POST /api/v0/auth/refresh. */
        AuthTokens: {
            /** @enum {string} */
            token_type: "Bearer";
            access_token: string;
            /** @description Seconds from this response until the access token expires. */
            access_token_expires_in: number;
            /** @description An opaque nrv_rt_ token. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the session ends; refreshing never extends it.
             */
            refresh_token_expires_at: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description The sign-in address, in any case, with or without surrounding blanks.
             */
            email: string;
            password: string;
        };
        RefreshRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        LogoutRequest: {
            /** @description The refresh_token of the last AuthTokens of the session. */
            refresh_token: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            display_name: string;
            /** @description An IANA time zone name. */
            user_timezone: string;
            /** @description Null until uploads arrive (M5). */
            avatar_url: string | null;
            /** @description Null until uploads arrive (M5). */
            cover_image_url: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserUpdate: {
            /** @description At most 255 characters, without a web address. */
            first_name?: string;
            /** @description At most 255 characters, without a web address. */
            last_name?: string;
            /** @description 1–255 characters. */
            display_name?: string;
            /** @description An IANA time zone name, e.g. from GET /api/v0/timezones. */
            user_timezone?: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @enum {string} */
        Theme: "system" | "light" | "dark" | "light-contrast" | "dark-contrast";
        /**
         * @description The language of the web UI.
         * @enum {string}
         */
        Language: "en" | "zh-CN";
        /**
         * @description The first day of the week, 0 Sunday to 6 Saturday.
         * @enum {integer}
         */
        StartOfTheWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        OnboardingSteps: {
            profile_complete: boolean;
            workspace_create: boolean;
            workspace_invite: boolean;
            workspace_join: boolean;
        };
        Profile: {
            theme: components["schemas"]["Theme"];
            language: components["schemas"]["Language"];
            start_of_the_week: components["schemas"]["StartOfTheWeek"];
            onboarding_step: components["schemas"]["OnboardingSteps"];
            is_onboarded: boolean;
            is_tour_completed: boolean;
            /**
             * Format: uuid
             * @description The workspace the web app opens last; null for none. It is not checked to exist.
             */
            last_workspace_id: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description The steps to set; the others keep their values. */
        OnboardingStepsUpdate: {
            profile_complete?: boolean;
            workspace_create?: boolean;
            workspace_invite?: boolean;
            workspace_join?: boolean;
        };
        ProfileUpdate: {
            theme?: components["schemas"]["Theme"];
            language?: components["schemas"]["Language"];
            start_of_the_week?: components["schemas"]["StartOfTheWeek"];
            onboarding_step?: components["schemas"]["OnboardingStepsUpdate"];
            is_onboarded?: boolean;
            is_tour_completed?: boolean;
            /**
             * Format: uuid
             * @description Null clears it.
             */
            last_workspace_id?: string | null;
        };
        /** @description A personal access token as lists show it. The token itself appears only in ApiTokenCreated. */
        ApiToken: {
            /** Format: uuid */
            id: string;
            label: string;
            description: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expired_at: string | null;
            /**
             * Format: date-time
             * @description When the token last authenticated a request, to the minute; null when it never has.
             */
            last_used: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description The cursor of the next page; null on the last page. */
        NextCursor: string | null;
        ApiTokenPage: {
            data: components["schemas"]["ApiToken"][];
            next_cursor: components["schemas"]["NextCursor"];
        };
        ApiTokenCreate: {
            /** @description 1–255 characters; 32 hexadecimal digits are made up when it is absent. */
            label?: string;
            description?: string;
            /**
             * Format: date-time
             * @description A time in the future; absent or null for a token that never expires.
             */
            expired_at?: string | null;
        };
        /** @description A new personal access token: the fields of ApiToken, and the token itself, which is shown this once and cannot be read again. */
        ApiTokenCreated: {
            /** Format: uuid */
            id: string;
            label: string;
            description: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expired_at: string | null;
            /**
             * Format: date-time
             * @description Null; the token has not been used yet.
             */
            last_used: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description The token, nrv_pat_ and 43 more characters. */
            token: string;
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
            /** @description Whether anyone may register (auth.signup_enabled). */
            signup_enabled: boolean;
            /** @description Whether workspaces can be created (workspace.creation_enabled). */
            workspace_creation_enabled: boolean;
            /** @description The largest file an upload may have, in bytes (files.size_limit). */
            file_size_limit: number;
        };
        Timezone: {
            /** @description A place in the time zone, e.g. Beijing. */
            label: string;
            /**
             * @description The IANA name, what user_timezone takes.
             * @example Asia/Shanghai
             */
            value: string;
            /**
             * @description The offset at the time of the request.
             * @example UTC+08:00
             */
            utc_offset: string;
            /**
             * @description The same offset, written from GMT.
             * @example GMT+08:00
             */
            gmt_offset: string;
        };
        TimezoneList: {
            data: components["schemas"]["Timezone"][];
        };
        /**
         * @description A member's role in a workspace, 5 guest, 15 member, 20 admin.
         * @enum {integer}
         */
        WorkspaceRole: 5 | 15 | 20;
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Lower case; it never changes. */
            slug: string;
            /** @description One of OrganizationSize's values; null when none was given. */
            organization_size: string | null;
            /** @description An IANA time zone name. */
            timezone: string;
            /** @description Null until uploads arrive (M5). */
            logo_url: string | null;
            role: components["schemas"]["WorkspaceRole"];
            /** @description The number of active members. */
            total_members: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkspaceList: {
            data: components["schemas"]["Workspace"][];
        };
        /**
         * @description The size of the organization, as the web app's form offers it.
         * @enum {string}
         */
        OrganizationSize: "Just myself" | "2-10" | "11-50" | "51-200" | "201-500" | "500+";
        WorkspaceCreate: {
            /** @description 1–80 characters, with a letter or a digit, without a web address. */
            name: string;
            /** @description 1–48 lower-case letters, digits, - and _; not reserved. */
            slug: string;
            organization_size?: components["schemas"]["OrganizationSize"];
            /** @description An IANA time zone name, e.g. from GET /api/v0/timezones; UTC when not given. */
            timezone?: string;
        };
        /** @description Changes the fields it names; a field left out keeps its value. organization_size cannot be set to null. */
        WorkspaceUpdate: {
            /** @description 1–80 characters, with a letter or a digit, without a web address. */
            name?: string;
            organization_size?: components["schemas"]["OrganizationSize"];
            /** @description An IANA time zone name. */
            timezone?: string;
        };
        /** @description A member's public profile, embedded in the membership: the one way v0 shows other accounts (M3 design 5.2). */
        MemberUser: {
            /** Format: uuid */
            id: string;
            display_name: string;
            first_name: string;
            last_name: string;
            /** @description Null until uploads arrive (M5). */
            avatar_url: string | null;
            /** @description The member's address for a caller who is an admin or a member; null for a guest. */
            email: string | null;
        };
        WorkspaceMember: {
            /**
             * Format: uuid
             * @description The membership's id, which /workspace-members/{workspace_member_id} names.
             */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            role: components["schemas"]["WorkspaceRole"];
            /** @description False once the membership has ended. */
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            member: components["schemas"]["MemberUser"];
        };
        WorkspaceMemberList: {
            data: components["schemas"]["WorkspaceMember"][];
        };
        /** @description An invitation of an address to the workspace, pending or declined (responded_at set). Only who may manage the workspace's invitations is given one, with the token of its link: /workspace-invitations?invitation_id={id}&token={token}. */
        WorkspaceInvitation: {
            /**
             * Format: uuid
             * @description The invitation's id, the link's invitation_id.
             */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            /** @description The address invited, normalized. */
            email: string;
            role: components["schemas"]["WorkspaceRole"];
            /** @description False; an invitation is deleted as it is accepted, and never listed again. */
            accepted: boolean;
            /**
             * Format: date-time
             * @description When the invitation was declined; null while it is pending.
             */
            responded_at: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: uuid
             * @description The account that invited; null once that account is gone.
             */
            created_by_id: string | null;
            /** @description nrv_inv_ and 22 base64url characters. The server does not store it: it computes it again from the invitation's id with a key derived from the instance's signing key, so a new signing key gives every invitation a new token and voids the old links. */
            token: string;
        };
        WorkspaceInvitationList: {
            data: components["schemas"]["WorkspaceInvitation"][];
        };
        InvitationCreate: {
            /** @description An e-mail address; it is normalized as at registration. */
            email: string;
            role: components["schemas"]["WorkspaceRole"];
        };
        WorkspaceInvitationsCreate: {
            /** @description 1–100 invitations, created all together or not at all. */
            invitations: components["schemas"]["InvitationCreate"][];
        };
        WorkspaceMemberUpdate: {
            role: components["schemas"]["WorkspaceRole"];
        };
        /** @description What an invitation's link shows whoever holds it. The workspace's fields are flat: the holder cannot read the workspace itself. There is no address: the holder of a link does not learn which address to register with. */
        InvitationPreview: {
            /** Format: uuid */
            id: string;
            role: components["schemas"]["WorkspaceRole"];
            /** @description True once the invitation was declined; it can no longer be answered. */
            declined: boolean;
            workspace_name: string;
            workspace_slug: string;
            /** @description Null until uploads arrive (M5). */
            workspace_logo_url: string | null;
        };
        WorkspaceInvitationUpdate: {
            role: components["schemas"]["WorkspaceRole"];
        };
        InvitationResponse: {
            /** @description The token of the invitation's link (WorkspaceInvitation.token). */
            token: string;
        };
        SlugAvailability: {
            available: boolean;
            /**
             * @description Why the slug is not available; absent when it is.
             * @enum {string}
             */
            reason?: "invalid" | "reserved" | "taken";
        };
        /**
         * @description How the sidebar shows the projects, as sections one under another or as tabs.
         * @enum {string}
         */
        NavigationControlPreference: "ACCORDION" | "TABBED";
        /** @description How many projects the sidebar shows before "more"; 0 shows them all. */
        NavigationProjectLimit: number;
        WorkspacePreferences: {
            navigation_control_preference: components["schemas"]["NavigationControlPreference"];
            navigation_project_limit: components["schemas"]["NavigationProjectLimit"];
        };
        WorkspacePreferencesUpdate: {
            navigation_control_preference?: components["schemas"]["NavigationControlPreference"];
            navigation_project_limit?: components["schemas"]["NavigationProjectLimit"];
        };
        /**
         * @description Who sees the project besides its members and the workspace's admins: 0 private, nobody; 2 public, the workspace's members too.
         * @enum {integer}
         */
        ProjectNetwork: 0 | 2;
        LogoEmoji: {
            /** @description The emoji, as the web app's picker gives it. */
            value?: string;
            /** @description The address of a custom emoji. */
            url?: string;
        };
        LogoIcon: {
            name?: string;
            color?: string;
            background_color?: string;
        };
        /** @description A project's icon, the web app's TLogoProps: every field optional, and {} no icon. */
        LogoProps: {
            /**
             * @description Which of the two icons the project shows.
             * @enum {string}
             */
            in_use?: "emoji" | "icon";
            emoji?: components["schemas"]["LogoEmoji"];
            icon?: components["schemas"]["LogoIcon"];
        };
        /**
         * @description A member's role in a project, 5 guest, 15 member, 20 admin.
         * @enum {integer}
         */
        ProjectRole: 5 | 15 | 20;
        /** @description A project, as the caller sees it: member_role and sort_order are his, null when he is not an active member. */
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            name: string;
            description: string;
            /** @description Upper case; it prefixes the numbers of the project's work items. */
            identifier: string;
            network: components["schemas"]["ProjectNetwork"];
            /** Format: uuid */
            project_lead_id: string | null;
            /**
             * Format: uuid
             * @description Whom a new work item is assigned to when nobody is given.
             */
            default_assignee_id: string | null;
            /** @description Whether the project shows cycles. */
            cycle_view: boolean;
            /** @description Whether the project shows modules. */
            module_view: boolean;
            /** @description Whether the project shows views. */
            issue_views_view: boolean;
            /** @description Whether the project shows intake. */
            intake_view: boolean;
            /** @description Whether the project's guests see every work item, not only their own. */
            guest_view_all_features: boolean;
            /** @description After how many months a closed work item is archived, 0–12; 0 never. */
            archive_in: number;
            /**
             * Format: date-time
             * @description When the project was archived; null while it is not.
             */
            archived_at: string | null;
            logo_props: components["schemas"]["LogoProps"];
            /** @description An IANA time zone name. */
            timezone: string;
            /** @description Null until uploads arrive (M5). */
            cover_image_url: string | null;
            /** @description The caller's role in the project; null when he is not an active member. */
            member_role: components["schemas"]["ProjectRole"] | null;
            /** @description The project's place in the caller's sidebar, lowest first; null when he is not an active member. */
            sort_order: number | null;
            /** @description The accounts of the active members, in the order they joined, then by id. */
            member_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectList: {
            data: components["schemas"]["Project"][];
        };
        ProjectCreate: {
            /** @description 1–255 characters, not all spaces, without any of & + , : ; $ ^ } { * = ? @ # | ' < > . ( ) % ! - */
            name: string;
            /** @description 1–10 of A-Z, 0-9 and ÇŞĞİÖÜ, once upper-cased. */
            identifier: string;
            description?: string;
            network?: components["schemas"]["ProjectNetwork"];
            /**
             * Format: uuid
             * @description An active admin or member of the workspace; he becomes an admin of the project.
             */
            project_lead_id?: string;
            logo_props?: components["schemas"]["LogoProps"];
            /** @description An IANA time zone name, e.g. from GET /api/v0/timezones; the workspace's when not given. */
            timezone?: string;
        };
        IdentifierAvailability: {
            available: boolean;
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                /** @description Sent with every 401 (RFC 9110 15.5.2): Bearer error="invalid_token" (RFC 6750 3) when the bearer token sent is refused before the operation runs, being invalid or expired; plain Bearer for every other 401, including a credential that the operation finds revoked while it runs. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The page size, 1–100; 50 when absent. Outside that range the answer is 422 validation_failed on limit. */
        Limit: number;
        /** @description The next_cursor of the page before; absent for the first page. A cursor that does not decode, has an unknown version or a payload of another shape than this list's, or is not spelled as the server writes it is 400 bad_request on cursor. */
        Cursor: string;
        /** @description A workspace's slug, as in the web app's address. */
        Slug: string;
        /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
        InvitationID: string;
        /** @description A project's id (Project.id). */
        ProjectID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type RegisterInvitation = components['schemas']['RegisterInvitation'];
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type FieldError = components['schemas']['FieldError'];
export type Problem = components['schemas']['Problem'];
export type AuthTokens = components['schemas']['AuthTokens'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type RefreshRequest = components['schemas']['RefreshRequest'];
export type LogoutRequest = components['schemas']['LogoutRequest'];
export type User = components['schemas']['User'];
export type UserUpdate = components['schemas']['UserUpdate'];
export type ChangePasswordRequest = components['schemas']['ChangePasswordRequest'];
export type Theme = components['schemas']['Theme'];
export type Language = components['schemas']['Language'];
export type StartOfTheWeek = components['schemas']['StartOfTheWeek'];
export type OnboardingSteps = components['schemas']['OnboardingSteps'];
export type Profile = components['schemas']['Profile'];
export type OnboardingStepsUpdate = components['schemas']['OnboardingStepsUpdate'];
export type ProfileUpdate = components['schemas']['ProfileUpdate'];
export type ApiToken = components['schemas']['ApiToken'];
export type NextCursor = components['schemas']['NextCursor'];
export type ApiTokenPage = components['schemas']['ApiTokenPage'];
export type ApiTokenCreate = components['schemas']['ApiTokenCreate'];
export type ApiTokenCreated = components['schemas']['ApiTokenCreated'];
export type InstanceInfo = components['schemas']['InstanceInfo'];
export type Timezone = components['schemas']['Timezone'];
export type TimezoneList = components['schemas']['TimezoneList'];
export type WorkspaceRole = components['schemas']['WorkspaceRole'];
export type Workspace = components['schemas']['Workspace'];
export type WorkspaceList = components['schemas']['WorkspaceList'];
export type OrganizationSize = components['schemas']['OrganizationSize'];
export type WorkspaceCreate = components['schemas']['WorkspaceCreate'];
export type WorkspaceUpdate = components['schemas']['WorkspaceUpdate'];
export type MemberUser = components['schemas']['MemberUser'];
export type WorkspaceMember = components['schemas']['WorkspaceMember'];
export type WorkspaceMemberList = components['schemas']['WorkspaceMemberList'];
export type WorkspaceInvitation = components['schemas']['WorkspaceInvitation'];
export type WorkspaceInvitationList = components['schemas']['WorkspaceInvitationList'];
export type InvitationCreate = components['schemas']['InvitationCreate'];
export type WorkspaceInvitationsCreate = components['schemas']['WorkspaceInvitationsCreate'];
export type WorkspaceMemberUpdate = components['schemas']['WorkspaceMemberUpdate'];
export type InvitationPreview = components['schemas']['InvitationPreview'];
export type WorkspaceInvitationUpdate = components['schemas']['WorkspaceInvitationUpdate'];
export type InvitationResponse = components['schemas']['InvitationResponse'];
export type SlugAvailability = components['schemas']['SlugAvailability'];
export type NavigationControlPreference = components['schemas']['NavigationControlPreference'];
export type NavigationProjectLimit = components['schemas']['NavigationProjectLimit'];
export type WorkspacePreferences = components['schemas']['WorkspacePreferences'];
export type WorkspacePreferencesUpdate = components['schemas']['WorkspacePreferencesUpdate'];
export type ProjectNetwork = components['schemas']['ProjectNetwork'];
export type LogoEmoji = components['schemas']['LogoEmoji'];
export type LogoIcon = components['schemas']['LogoIcon'];
export type LogoProps = components['schemas']['LogoProps'];
export type ProjectRole = components['schemas']['ProjectRole'];
export type Project = components['schemas']['Project'];
export type ProjectList = components['schemas']['ProjectList'];
export type ProjectCreate = components['schemas']['ProjectCreate'];
export type IdentifierAvailability = components['schemas']['IdentifierAvailability'];
export type ResponseProblem = components['responses']['Problem'];
export type ParameterLimit = components['parameters']['Limit'];
export type ParameterCursor = components['parameters']['Cursor'];
export type ParameterSlug = components['parameters']['Slug'];
export type ParameterInvitationId = components['parameters']['InvitationID'];
export type ParameterProjectId = components['parameters']['ProjectID'];
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The new session's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The session's next tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Done, whatever the token was. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The caller's account, changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deactivateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's preferences. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The caller's preferences, changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listApiTokens: {
        parameters: {
            query?: {
                /** @description The page size, 1–100; 50 when absent. Outside that range the answer is 422 validation_failed on limit. */
                limit?: components["parameters"]["Limit"];
                /** @description The next_cursor of the page before; absent for the first page. A cursor that does not decode, has an unknown version or a payload of another shape than this list's, or is not spelled as the server writes it is 400 bad_request on cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description The new token, with the token itself. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTimezones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The time zones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimezoneList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description The new workspace; the caller is its admin. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace, with the caller's role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace is deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description The workspace as changed, with the caller's role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaceInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's invitations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInvitationList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkspaceInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInvitationsCreate"];
            };
        };
        responses: {
            /** @description The new invitations, in the request's order. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInvitationList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A membership's id (WorkspaceMember.id), not the member's account id. */
                workspace_member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberUpdate"];
            };
        };
        responses: {
            /** @description The membership with its new role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkspaceInvitation: {
        parameters: {
            query: {
                /** @description The token of the invitation's link (WorkspaceInvitation.token). */
                token: string;
            };
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation as its link shows it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation is deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInvitationUpdate"];
            };
        };
        responses: {
            /** @description The invitation with its new role, and the token of its link. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInvitation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    acceptWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationResponse"];
            };
        };
        responses: {
            /** @description The workspace the caller is a member of, with his role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    declineWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An invitation's id (WorkspaceInvitation.id), the link's invitation_id. */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationResponse"];
            };
        };
        responses: {
            /** @description The invitation is declined. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    checkWorkspaceSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the slug is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlugAvailability"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkspacePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's settings in the workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePreferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkspacePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePreferencesUpdate"];
            };
        };
        responses: {
            /** @description The caller's settings in the workspace, as changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePreferences"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description true lists the archived projects alone; false, or no value, the others. */
                archived?: boolean;
            };
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description The new project, as the caller, its admin, sees it. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    checkProjectIdentifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A workspace's slug, as in the web app's address. */
                slug: components["parameters"]["Slug"];
                /** @description An identifier asked about, in any case. */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the identifier is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentifierAvailability"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A project's id (Project.id). */
                project_id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project, as the caller sees it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
