package migrations_test

// projectNames are the constraints and indexes of the project module's
// tables (M3 design 4.6–4.9), as TestConstraintAndIndexNames reads them:
// the part of its want that the migrations 00010–00013 add.
var projectNames = []string{
	"project_members_created_by_id_fkey f n",
	"project_members_member_id_fkey f c",
	"project_members_member_id_idx iw",
	"project_members_pkey iu",
	"project_members_pkey p",
	"project_members_project_id_fkey f c",
	"project_members_project_id_idx i",
	"project_members_project_id_member_id_key iuw",
	"project_members_role_check c",
	"project_members_updated_by_id_fkey f n",
	"project_members_workspace_id_fkey f c",
	"project_members_workspace_id_idx i",
	"project_user_properties_created_by_id_fkey f n",
	"project_user_properties_pkey iu",
	"project_user_properties_pkey p",
	"project_user_properties_preferences_check c",
	"project_user_properties_project_id_fkey f c",
	"project_user_properties_project_id_idx i",
	"project_user_properties_project_id_user_id_key iuw",
	"project_user_properties_updated_by_id_fkey f n",
	"project_user_properties_user_id_fkey f c",
	"project_user_properties_workspace_id_fkey f c",
	"project_user_properties_workspace_id_idx i",
	"projects_archive_in_check c",
	"projects_created_by_id_fkey f n",
	"projects_default_assignee_id_fkey f n",
	"projects_identifier_check c",
	"projects_last_issue_sequence_check c",
	"projects_logo_props_check c",
	"projects_name_check c",
	"projects_network_check c",
	"projects_pkey iu",
	"projects_pkey p",
	"projects_project_lead_id_fkey f n",
	"projects_updated_by_id_fkey f n",
	"projects_workspace_id_fkey f c",
	"projects_workspace_id_identifier_key iuw",
	"projects_workspace_id_idx i",
	"projects_workspace_id_name_key iuw",
	"states_created_by_id_fkey f n",
	"states_group_check c",
	"states_name_check c",
	"states_pkey iu",
	"states_pkey p",
	"states_project_id_default_key iuw",
	"states_project_id_fkey f c",
	"states_project_id_idx i",
	"states_project_id_name_key iuw",
	"states_project_id_triage_key iuw",
	"states_updated_by_id_fkey f n",
	"states_workspace_id_fkey f c",
	"states_workspace_id_idx i",
}
